### ISSUE TITLE
Tool crashes if specified file is not available

### ISSUE THREAD

**Issue by Elscha** [SSE-LinuxAnalysis/KbuildCrawler#2]
If specified file does not exist, KbuildCrawler prints an error log to System.err (not to the logger). For example:
```
Exception in thread "ExtractorDataDuplicator" java.lang.RuntimeException: net.ssehub.kernel_haven.SetUpException: Non-existing file specified in code.extractor.files: drivers/phy/phy-exynos-mipi-video.c
        at net.ssehub.kernel_haven.provider.AbstractProvider.startExtractorIfNotRunning(AbstractProvider.java:192)
        at net.ssehub.kernel_haven.provider.AbstractProvider.getNextResult(AbstractProvider.java:227)
        at net.ssehub.kernel_haven.analysis.PipelineAnalysis$ExtractorDataDuplicator.run(PipelineAnalysis.java:276)
        at java.lang.Thread.run(Thread.java:748)
Caused by: net.ssehub.kernel_haven.SetUpException: Non-existing file specified in code.extractor.files: drivers/phy/phy-exynos-mipi-video.c
        at net.ssehub.kernel_haven.code_model.CodeModelProvider.getTargets(CodeModelProvider.java:44)
        at net.ssehub.kernel_haven.provider.AbstractProvider.start(AbstractProvider.java:153)
        at net.ssehub.kernel_haven.provider.AbstractProvider.startExtractorIfNotRunning(AbstractProvider.java:188)
        ... 3 more
```

**Comment by adam-sse** [comment]
851cf97b70a5ec07a7c1ab91fa763e7626f15e18
